Question 1

In [78]:
import pandas as pd
import numpy as np

df = pd.read_csv('D1[1].csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1544 entries, 0 to 1543
Data columns (total 6 columns):
patient_id    1544 non-null object
global_num    975 non-null float64
date          1544 non-null object
location      1544 non-null object
latitude      1544 non-null float64
longitude     1544 non-null float64
dtypes: float64(3), object(3)
memory usage: 72.5+ KB


In [2]:
df

patient_id  global_num        date                    location  \
0     P1000000501         2.0  22/04/2020       Chittorgarh_Rajasthan   
1     P1000000501         2.0  24/04/2020       Ratnagiri_Maharashtra   
2     P1000000502         5.0  26/04/2020          Pindwara_Rajasthan   
3     P1000000502         5.0  27/04/2020         Raipur_Chhattisgarh   
4     P1000000502         5.0  28/04/2020             Gokak_Karnataka   
...           ...         ...         ...                         ...   
1539  P9011000510         NaN  19/05/2020             Sagar_Karnataka   
1540  P9011000510         NaN  19/05/2020        Jorapokhar_Jharkhand   
1541  P9014000503         NaN  27/05/2020         Rewa_Madhya Pradesh   
1542  P9014000504         NaN  27/05/2020  Dharmavaram_Andhra Pradesh   
1543  P9015000503        41.0   2/12/2020         Asansol_West Bengal   

       latitude  longitude  
0     24.879999  74.629997  
1     16.994444  73.300003  
2     24.794500  73.055000  
3     21.250000  81.629997  
4     16.166700  74.833298  
...         ...        ...  
1539  14.167040  75.040298  
1540  22.422455  85.760651  
1541  24.530727  81.299110  
1542  14.413745  77.712616  
1543  23.673944  86.952393  

[1544 rows x 6 columns]

In [3]:
for col in df:
    print(df[col].unique())

['P1000000501' 'P1000000502' 'P1000000504' 'P1000000505' 'P1000000506'
 'P1000000507' 'P1000000508' 'P1000000509' 'P1000000510' 'P1000000511'
 'P1000000513' 'P1000000514' 'P1000000515' 'P1000000517' 'P1000000518'
 'P1000000520' 'P1000000521' 'P1000000522' 'P1000000523' 'P1000000524'
 'P1000000525' 'P1000000526' 'P1000000527' 'P1000000529' 'P1000000531'
 'P1000000532' 'P1000000533' 'P1000000534' 'P1000000535' 'P1000000537'
 'P1000000538' 'P1000000539' 'P1000000540' 'P1000000541' 'P1000000542'
 'P1000000543' 'P1000000544' 'P1000000545' 'P1000000546' 'P1000000547'
 'P1000000549' 'P1000000550' 'P1000000551' 'P1000000552' 'P1000000553'
 'P1000000554' 'P1000000555' 'P1000000556' 'P1000000558' 'P1000000559'
 'P1000000560' 'P1000000561' 'P1000000562' 'P1000000565' 'P1000000566'
 'P1000000567' 'P1000000568' 'P1000000570' 'P1000000571' 'P1000000572'
 'P1000000574' 'P1000000575' 'P1000000576' 'P1000000577' 'P1000000580'
 'P1000000581' 'P1000000582' 'P1000000583' 'P1000000584' 'P1000000585'
 'P100

In [4]:
df['patient_id'].value_counts()

P3013000501    6
P1000000555    5
P1000000535    5
P3013000502    5
P6100000519    5
              ..
P1600000521    1
P1100000600    1
P1000000509    1
P4100000542    1
P1000001093    1
Name: patient_id, Length: 911, dtype: int64

In [5]:
df['patient_id'].value_counts()
#appears there are 2 missing patient IDs as the lenght is 911 and there 
#is meant to be 913 unque patients

P3013000501    6
P1000000555    5
P1000000535    5
P3013000502    5
P6100000519    5
              ..
P1600000521    1
P1100000600    1
P1000000509    1
P4100000542    1
P1000001093    1
Name: patient_id, Length: 911, dtype: int64

In [6]:
df['location'].value_counts()
#location has correct amount

Sardarshahar_Rajasthan    134
Ranebennur_Karnataka       79
Lucknow_Uttar Pradesh      79
Ratnagiri_Maharashtra      57
Kollam_Kerala              54
                         ... 
Durgapur_West Bengal        1
Udgir_Maharashtra           1
Bihar Sharif_Bihar          1
Hinganghat_Maharashtra      1
Arvi_Maharashtra            1
Name: location, Length: 151, dtype: int64

In [7]:
df['global_num'].value_counts()

384.0     8
440.0     6
387.0     6
847.0     5
1295.0    5
         ..
9864.0    1
8612.0    1
9320.0    1
1800.0    1
3815.0    1
Name: global_num, Length: 575, dtype: int64

In [8]:
df.isnull().sum()
#so there is 569 nan values in global which is more then half
#I dont really know what this ID is for and how it differs to patient_id 
#so im going to drop it for now

patient_id      0
global_num    569
date            0
location        0
latitude        0
longitude       0
dtype: int64

In [9]:
df = df.drop(columns=['global_num'])
df

patient_id        date                    location   latitude  \
0     P1000000501  22/04/2020       Chittorgarh_Rajasthan  24.879999   
1     P1000000501  24/04/2020       Ratnagiri_Maharashtra  16.994444   
2     P1000000502  26/04/2020          Pindwara_Rajasthan  24.794500   
3     P1000000502  27/04/2020         Raipur_Chhattisgarh  21.250000   
4     P1000000502  28/04/2020             Gokak_Karnataka  16.166700   
...           ...         ...                         ...        ...   
1539  P9011000510  19/05/2020             Sagar_Karnataka  14.167040   
1540  P9011000510  19/05/2020        Jorapokhar_Jharkhand  22.422455   
1541  P9014000503  27/05/2020         Rewa_Madhya Pradesh  24.530727   
1542  P9014000504  27/05/2020  Dharmavaram_Andhra Pradesh  14.413745   
1543  P9015000503   2/12/2020         Asansol_West Bengal  23.673944   

      longitude  
0     74.629997  
1     73.300003  
2     73.055000  
3     81.629997  
4     74.833298  
...         ...  
1539  75.040298  
1540  85.760651  
1541  81.299110  
1542  77.712616  
1543  86.952393  

[1544 rows x 5 columns]

In [10]:
travel = df.groupby(['patient_id'])['location'].apply(list)
print(travel)

patient_id
P1000000501       [Chittorgarh_Rajasthan, Ratnagiri_Maharashtra]
P1000000502    [Pindwara_Rajasthan, Raipur_Chhattisgarh, Goka...
P1000000504                              [Lucknow_Uttar Pradesh]
P1000000505                              [Lucknow_Uttar Pradesh]
P1000000506                                        [Delhi_Delhi]
                                     ...                        
P9100000582                                      [Anand_Gujarat]
P9100000583    [Channapatna_Karnataka, Sivasagar_Assam, Jorap...
P9100000585                               [Ranaghat_West Bengal]
P9100000586                  [RL Infotechh & Solutions_Durgapur]
P9100000590             [Sardarshahar_Rajasthan, Pali_Rajasthan]
Name: location, Length: 911, dtype: object


In [11]:
pip install apyori

  Created wheel for apyori: filename=apyori-1.1.2-cp37-none-any.whl size=5979 sha256=588ba5bbc95e416e6cd73cd417de9c1db49c6e3bee151867b85914eed9108f6a
  Stored in directory: C:\Users\n9993304\AppData\Local\pip\Cache\wheels\5d\92\bb\474bbadbc8c0062b9eb168f69982a0443263f8ab1711a8cad0
Successfully built apyori
Note: you may need to restart the kernel to use updated packages.


In [12]:
from apyori import apriori
# type cast the transactions from pandas into normal list format and run apriori
travel_list = list(travel)
results = list(apriori(travel_list, min_support=0.01, min_confidence = 0.1))
# print first 5 rules
print(results[:5])

# I ended up using a min_support of 0.01 and min_confidence at 0.1 because these parameters produced the least redundent rules
# with all having a lift above > 1 while still representing a percentage of the data that is meaningful.

[RelationRecord(items=frozenset({'Sardarshahar_Rajasthan'}), support=0.14709110867178923, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Sardarshahar_Rajasthan'}), confidence=0.14709110867178923, lift=1.0)]), RelationRecord(items=frozenset({'Jorapokhar_Jharkhand', 'Channapatna_Karnataka'}), support=0.012074643249176729, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Channapatna_Karnataka'}), items_add=frozenset({'Jorapokhar_Jharkhand'}), confidence=0.21568627450980393, lift=5.45806100217865), OrderedStatistic(items_base=frozenset({'Jorapokhar_Jharkhand'}), items_add=frozenset({'Channapatna_Karnataka'}), confidence=0.3055555555555556, lift=5.45806100217865)]), RelationRecord(items=frozenset({'Sardarshahar_Rajasthan', 'Gokak_Karnataka'}), support=0.027442371020856202, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Gokak_Karnataka'}), items_add=frozenset({'Sardarshahar_Rajasthan'}), confidence=0.5, lift=3.399253731343284), Orde

In [13]:
def convert_apriori_results_to_pandas_df(results):
    rules = []
    for rule_set in results:
        for rule in rule_set.ordered_statistics:
            # items_base = left side of rules, items_add = right side
            # support, confidence and lift for respective rules
            rules.append([','.join(rule.items_base), ','.join(rule.items_add),
                rule_set.support, rule.confidence, rule.lift])
    # typecast it to pandas df
    return pd.DataFrame(rules, columns=['Left_side', 'Right_side', 'Support',
    'Confidence', 'Lift'])
result_df = convert_apriori_results_to_pandas_df(results)
result_df.head(10)

Left_side              Right_side   Support  Confidence  \
0                          Sardarshahar_Rajasthan  0.147091    0.147091   
1   Channapatna_Karnataka    Jorapokhar_Jharkhand  0.012075    0.215686   
2    Jorapokhar_Jharkhand   Channapatna_Karnataka  0.012075    0.305556   
3         Gokak_Karnataka  Sardarshahar_Rajasthan  0.027442    0.500000   
4  Sardarshahar_Rajasthan         Gokak_Karnataka  0.027442    0.186567   
5           Kollam_Kerala  Sardarshahar_Rajasthan  0.012075    0.203704   
6   Lucknow_Uttar Pradesh  Sardarshahar_Rajasthan  0.018661    0.215190   
7  Sardarshahar_Rajasthan   Lucknow_Uttar Pradesh  0.018661    0.126866   

       Lift  
0  1.000000  
1  5.458061  
2  5.458061  
3  3.399254  
4  3.399254  
5  1.384881  
6  1.462970  
7  1.462970

In [14]:
result_df = result_df.sort_values(by='Lift', ascending=False)
result_df.head(5)

Left_side              Right_side   Support  Confidence  \
1   Channapatna_Karnataka    Jorapokhar_Jharkhand  0.012075    0.215686   
2    Jorapokhar_Jharkhand   Channapatna_Karnataka  0.012075    0.305556   
3         Gokak_Karnataka  Sardarshahar_Rajasthan  0.027442    0.500000   
4  Sardarshahar_Rajasthan         Gokak_Karnataka  0.027442    0.186567   
7  Sardarshahar_Rajasthan   Lucknow_Uttar Pradesh  0.018661    0.126866   

       Lift  
1  5.458061  
2  5.458061  
3  3.399254  
4  3.399254  
7  1.462970

In [15]:
#sequential association mining can be done because the data is ordered by date in accending order, so each travel of 
# patient is sequential. The data does not have exact time but it is assumebed that patients with travel on the same day 
#is still ordered sequentially

transactions = df.groupby(['patient_id'])['location'].apply(list)
sequences = transactions.values.tolist()

# show the first 5 sequences
print(sequences[:5])


[['Chittorgarh_Rajasthan', 'Ratnagiri_Maharashtra'], ['Pindwara_Rajasthan', 'Raipur_Chhattisgarh', 'Gokak_Karnataka'], ['Lucknow_Uttar Pradesh'], ['Lucknow_Uttar Pradesh'], ['Delhi_Delhi']]


In [16]:
from collections import defaultdict
import subprocess
import re

''' Uses SPMF to find association rules in supplied transactions '''
def get_association_rules(sequences, min_sup, min_conf):
    # step 1: create required input for SPMF
    
    # prepare a dict to uniquely assign each item in the transactions to an int ID
    item_dict = defaultdict(int)
    output_dict = defaultdict(str)
    item_id = 1
    
    # write your sequences in SPMF format
    with open('seq_rule_input.txt', 'w+') as f:
        for sequence in sequences:
            z = []
            for itemset in sequence:
                # if there are multiple items in one itemset
                if isinstance(itemset, list):
                    for item in itemset:
                        if item not in item_dict:
                            item_dict[item] = item_id
                            item_id += 1

                        z.append(item_dict[item])
                else:
                    if itemset not in item_dict:
                        item_dict[itemset] = item_id
                        output_dict[str(item_id)] = itemset
                        item_id += 1
                    z.append(item_dict[itemset])
                    
                # end of itemset
                z.append(-1)
            
            # end of a sequence
            z.append(-2)
            f.write(' '.join([str(x) for x in z]))
            f.write('\n')
    
    # run SPMF with supplied parameters
    supp_param = '{}%'.format(int(min_sup * 100))
    conf_param = '{}%'.format(int(min_conf * 100))
    subprocess.call(['java', '-jar', 'spmf.jar', 'run', 'RuleGrowth', 
                     'seq_rule_input.txt', 'seq_rule_output.txt', 
                     supp_param, conf_param], shell=True)
    
    # read back the output rules
    outputs = open('seq_rule_output.txt', 'r').read().strip().split('\n')
    output_rules = []
    for rule in outputs:
        left, right, sup, conf = re.search(pattern=r'([0-9\,]+) ==> ([0-9\,]+) #SUP: ([0-9]+) #CONF: ([0-9\.]+)', string=rule).groups()
        sup = int(sup) / len(sequences)
        conf = float(conf)
        output_rules.append([[output_dict[x] for x in left.split(',')], [output_dict[x] for x in right.split(',')], sup, conf])
    
    # return pandas DataFrame
    return pd.DataFrame(output_rules, columns = ['Left_rule', 'Right_rule', 'Support', 'Confidence'])

In [21]:
get_association_rules(sequences, 0.01, 0.1)

Left_rule               Right_rule   Support  Confidence
0  [Sardarshahar_Rajasthan]        [Gokak_Karnataka]  0.026345    0.179104
1  [Sardarshahar_Rajasthan]  [Lucknow_Uttar Pradesh]  0.018661    0.126866
2   [Channapatna_Karnataka]   [Jorapokhar_Jharkhand]  0.010977    0.196078

Question 2

In [42]:
import pandas as pd
import numpy as np

# not skipping empty values, to demonstrate data preprocessing steps later
df = pd.read_csv('D2[1].csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36183 entries, 0 to 36182
Data columns (total 29 columns):
race                        35335 non-null object
gender                      36183 non-null object
age                         36174 non-null object
admission_type_id           36183 non-null int64
discharge_disposition_id    36183 non-null int64
admission_source_id         36183 non-null int64
time_in_hospital            36183 non-null int64
medical_specialty           36183 non-null object
num_lab_procedures          36183 non-null int64
num_procedures              36183 non-null int64
num_medications             36183 non-null int64
number_outpatient           36183 non-null int64
number_emergency            36183 non-null int64
number_inpatient            36183 non-null int64
number_diagnoses            36183 non-null int64
max_glu_serum               36183 non-null object
A1Cresult                   36183 non-null object
metformin                   36183 non-null object
re

In [43]:
for col in df:
    print(df[col].unique())

['Caucasian' 'AfricanAmerican' 'Hispanic' nan 'Other' 'Asian']
['Female' 'Male' 'Unknown/Invalid']
['[60-70)' '[80-90)' '[70-80)' '[40-50)' '[50-60)' '[90-100)' '[30-40)'
 '[20-30)' '[10-20)' '[0-10)' nan]
[2 3 1 5 6 8 7 4]
[ 1  2  6  3 22 11  7 23 13  4 15  9 28  5 19  8 25 14 24 18 27]
[ 1  7  5 17  4  2  3  6  9 10 22  8 14 11 25 13]
[ 4  8  2  7  3  6  5  1 13 12 11  9 10 14]
['InternalMedicine' 'Invalid' 'Cardiology' 'Emergency/Trauma' 'Neurology'
 'Surgery-General' 'Family/GeneralPractice'
 'Surgery-Cardiovascular/Thoracic' 'Surgery-Vascular' 'Oncology'
 'Osteopath' 'Surgery-Neuro' 'Radiologist' 'Nephrology' 'Pulmonology'
 'Orthopedics-Reconstructive' 'Gastroenterology' 'Surgery-Plastic'
 'Surgery-Pediatric' 'Psychiatry' 'Orthopedics' 'Urology'
 'Surgery-Cardiovascular' 'Gynecology' 'PhysicalMedicineandRehabilitation'
 'ObstetricsandGynecology' 'Hematology/Oncology' 'Podiatry'
 'Otolaryngology' 'Surgeon' 'Pediatrics' 'Psychology' 'Hematology'
 'OutreachServices' 'Endocrinology' '

In [44]:
df['race'].value_counts()

Caucasian          27776
AfricanAmerican     5764
Hispanic             806
Other                696
Asian                293
Name: race, dtype: int64

In [60]:
df['age'].unique()

array(['[60-70)', '[80-90)', '[70-80)', '[40-50)', '[50-60)', '[90-100)',
       '[30-40)', '[20-30)', '[10-20)', '[0-10)', nan], dtype=object)

In [46]:
df['age'].value_counts()
#said age had nan in unique but none could be found
#no edits were made

[70-80)     8990
[60-70)     8232
[80-90)     6386
[50-60)     6159
[40-50)     3328
[30-40)     1245
[90-100)    1072
[20-30)      561
[10-20)      179
[0-10)        22
Name: age, dtype: int64

In [58]:
df['chlorpropamide'].unique()

array(['No', nan, 'Steady'], dtype=object)

In [59]:
df['chlorpropamide'].value_counts()
#same thing for chlorpromaide as there was a nan listed in the unique fucntion but none where found in the value counts
#no edits were made

No        36160
Steady       14
Name: chlorpropamide, dtype: int64

In [61]:
df['gender'].unique()

array(['Female', 'Male', 'Unknown/Invalid'], dtype=object)

In [62]:
df['gender'].value_counts()

Female             19196
Male               16984
Unknown/Invalid        3
Name: gender, dtype: int64

In [63]:
indexNames = df[ df['gender'] == 'Unknown/Invalid' ].index
df.drop(indexNames , inplace=True)
#the choice to drop invalid/unknown gender was made as for one the varaible had only 4 people and two because biological
#gender is a predicting factor in diabetes making unknown/invalid an uncontrolled variable in the data

In [64]:
df['gender'].value_counts()

Female    19196
Male      16984
Name: gender, dtype: int64

In [77]:
df['gender'].mode()

0    Female
dtype: object

Question 3


Question 4

Question 5