In [188]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('D1(1).csv')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51766 entries, 0 to 51765
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   encounter_id              51766 non-null  int64 
 1   patient_nbr               51766 non-null  int64 
 2   race                      51766 non-null  object
 3   gender                    51766 non-null  object
 4   age                       51766 non-null  object
 5   weight                    51766 non-null  object
 6   admission_type_id         51766 non-null  int64 
 7   discharge_disposition_id  51766 non-null  int64 
 8   admission_source_id       51766 non-null  int64 
 9   time_in_hospital          51766 non-null  int64 
 10  payer_code                51766 non-null  object
 11  medical_specialty         51766 non-null  object
 12  num_lab_procedures        51766 non-null  int64 
 13  num_procedures            51766 non-null  int64 
 14  num_medications       

In [189]:
df['admission_type_id'] = df['admission_type_id'].astype(str)
df['discharge_disposition_id'] = df['discharge_disposition_id'].astype(str)
df['admission_source_id'] = df['admission_source_id'].astype(str)
# these are categorical data so I changed them to strings 

In [190]:
df['admission_type_id'].unique()
#done this to demonstrate its now a string

array(['2', '3', '1', '5', '6', '8', '7', '4'], dtype=object)

In [191]:
for col in df:
    print(df[col].unique())
#for loop to display all unique vaues so we can see what colomns have missing data.

[150645834 150646782 150659562 ... 443854148 443857166 443867222]
[ 66173058 104923647  30917367 ... 140199494 120975314 175429310]
['Caucasian' 'AfricanAmerican' 'Hispanic' '?' 'Other' 'Asian']
['Female' 'Male' 'Unknown/Invalid']
['[60-70)' '[80-90)' '[70-80)' '[40-50)' '[50-60)' '[90-100)' '[30-40)'
 '[20-30)' '[10-20)' '[0-10)' '?']
['?' '[100-125)' '[50-75)' '[75-100)' '[0-25)' '[125-150)' '[25-50)'
 '[150-175)' '[175-200)' '>200']
['2' '3' '1' '5' '6' '8' '7' '4']
['1' '2' '6' '3' '22' '11' '7' '23' '13' '4' '15' '9' '28' '5' '19' '8'
 '25' '14' '24' '27' '18']
['1' '7' '5' '17' '4' '2' '3' '6' '9' '10' '22' '20' '8' '14' '11' '25'
 '13']
[ 4  8  2  7  3  6  5  1 13 12 11  9 10 14]
['?' 'MD' 'BC' 'MC' 'HM' 'CP' 'SP' 'OG' 'UN' 'DM' 'CM' 'PO' 'SI' 'WC' 'CH'
 'OT' 'MP' 'FR']
['InternalMedicine' '?' 'Cardiology' 'Emergency/Trauma' 'Neurology'
 'Surgery-General' 'Family/GeneralPractice'
 'Surgery-Cardiovascular/Thoracic' 'Surgery-Vascular' 'Oncology'
 'Osteopath' 'Surgery-Neuro' 'Radio

In [192]:
df['weight'].value_counts()

?            50431
[75-100)       542
[50-75)        347
[100-125)      309
[125-150)       72
[25-50)         29
[150-175)       18
[0-25)          11
[175-200)        5
>200             2
Name: weight, dtype: int64

In [193]:
df = df.drop(columns=['weight','patient_nbr', 'encounter_id', 'acetohexamide', 'tolbutamide']) 
## weight was dropped because it had more missing values then it did filled, patient_nbr and encouter_id were dropped as we felt they were not needed. Acetohexamide and tolbitamide were dropped because it was not percribed to anyone

In [194]:
df['chlorpropamide'].value_counts() 
#check the amount of missing values in chlorpropamide. Determined they were small enough to remove

No        51738
Steady       18
?             9
Up            1
Name: chlorpropamide, dtype: int64

In [195]:
indexNames = df[ df['chlorpropamide'] == '?' ].index
df.drop(indexNames , inplace=True)
#remove "?" values from chlorpromaide

In [196]:
df['chlorpropamide'].value_counts()
#checking the values were removed

No        51738
Steady       18
Up            1
Name: chlorpropamide, dtype: int64

In [197]:
df['race'].value_counts()
#check the missing values of race. The missing values were large so chose to replace them with the mode (Caucasian) as it is categorical data

Caucasian          40382
AfricanAmerican     8068
Hispanic            1018
?                   1015
Other                896
Asian                378
Name: race, dtype: int64

In [198]:
df['race'].mode()

0    Caucasian
dtype: object

In [199]:
df['race'] = df['race'].replace(['?'],'Caucasian')
# replacing "?" with caucasian 

In [200]:
df['race'].value_counts()
#showing that its done

Caucasian          41397
AfricanAmerican     8068
Hispanic            1018
Other                896
Asian                378
Name: race, dtype: int64

In [201]:
df['gender'].value_counts()
#checking missing values in gender

Female             27714
Male               24039
Unknown/Invalid        4
Name: gender, dtype: int64

In [202]:
indexNames = df[ df['gender'] == 'Unknown/Invalid' ].index
df.drop(indexNames , inplace=True)
#the choice to drop invalid/unknown gender was made as for one the varaible had only 4 people and two because biological gender is a predicting factor in diabetes making unknown/invalid an uncontrolled variable in the data

In [203]:
df['gender'].value_counts()
#showing that unknown/invaid was removed

Female    27714
Male      24039
Name: gender, dtype: int64

In [204]:
df['age'].value_counts()
#showing the unknown varaibles for age, small enough to remove

[70-80)     12969
[60-70)     11612
[80-90)      9670
[50-60)      8479
[40-50)      4619
[30-40)      1717
[90-100)     1616
[20-30)       815
[10-20)       223
[0-10)         23
?              10
Name: age, dtype: int64

In [205]:
indexNames = df[ df['age'] == '?' ].index
df.drop(indexNames , inplace=True)
#removing "?"

In [206]:
df['age'].value_counts()
#showing that ? has been removed

[70-80)     12969
[60-70)     11612
[80-90)      9670
[50-60)      8479
[40-50)      4619
[30-40)      1717
[90-100)     1616
[20-30)       815
[10-20)       223
[0-10)         23
Name: age, dtype: int64

In [207]:
df['payer_code'].value_counts()
# looking at the payer code a large amount are mising varaibles so decided to drop them as i imagine it wont effect the datat to much.

MC    23039
?      7599
HM     4698
SP     3808
BC     3164
MD     2532
CP     1799
CM     1696
UN     1190
OG      879
PO      511
DM      412
CH      127
WC      100
OT       83
MP       79
SI       26
FR        1
Name: payer_code, dtype: int64

In [208]:
df = df.drop(columns=['payer_code'])
#removing the the payer_code column

In [209]:
for col in df:
    print(df[col].unique())
#redisplaying the unique values and there should be no ? and dropped columns have been dropped

['Caucasian' 'AfricanAmerican' 'Hispanic' 'Other' 'Asian']
['Female' 'Male']
['[60-70)' '[80-90)' '[70-80)' '[40-50)' '[50-60)' '[90-100)' '[30-40)'
 '[20-30)' '[10-20)' '[0-10)']
['2' '3' '1' '5' '6' '8' '7' '4']
['1' '2' '6' '3' '22' '11' '7' '23' '13' '4' '15' '9' '28' '5' '19' '8'
 '25' '14' '24' '27' '18']
['1' '7' '5' '17' '4' '2' '3' '6' '9' '10' '22' '20' '8' '14' '11' '25'
 '13']
[ 4  8  2  7  3  6  5  1 13 12 11  9 10 14]
['InternalMedicine' '?' 'Cardiology' 'Emergency/Trauma' 'Neurology'
 'Surgery-General' 'Family/GeneralPractice'
 'Surgery-Cardiovascular/Thoracic' 'Oncology' 'Osteopath' 'Surgery-Neuro'
 'Radiologist' 'Nephrology' 'Pulmonology' 'Orthopedics-Reconstructive'
 'Gastroenterology' 'Surgery-Vascular' 'Surgery-Plastic'
 'Surgery-Pediatric' 'Psychiatry' 'Orthopedics' 'Urology'
 'Surgery-Cardiovascular' 'Gynecology' 'PhysicalMedicineandRehabilitation'
 'ObstetricsandGynecology' 'Hematology/Oncology' 'Podiatry'
 'Otolaryngology' 'Surgeon' 'Pediatrics' 'Psychology' 'He